version: '3'
services:
  api:
    image: clean-node-ts-api
    container_name: api-container
    build: .
    restart: always
    ports:
      - 5050:5050
      - 9222:9222
    command: npm run debug
    volumes:
      - ./dist:/usr/clean-node-ts-api/dist
      - ./package.json:/usr/clean-node-ts-api/package.json